// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/proto/core/v1/meta.proto

package corev1

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	reflect "reflect"
	strings "strings"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Meta ...
type Meta struct {
	CreatedTime *time.Time `protobuf:"bytes,1,opt,name=created_time,json=createdTime,proto3,stdtime" json:"created_time,omitempty"`
	UpdatedTime *time.Time `protobuf:"bytes,2,opt,name=updated_time,json=updatedTime,proto3,stdtime" json:"updated_time,omitempty"`
	DeletedTime *time.Time `protobuf:"bytes,3,opt,name=deleted_time,json=deletedTime,proto3,stdtime" json:"deleted_time,omitempty"`
}

func (m *Meta) Reset()      { *m = Meta{} }
func (*Meta) ProtoMessage() {}
func (*Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf797db7e4df907, []int{0}
}
func (m *Meta) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Meta.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meta.Merge(m, src)
}
func (m *Meta) XXX_Size() int {
	return m.Size()
}
func (m *Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_Meta proto.InternalMessageInfo

func (m *Meta) GetCreatedTime() *time.Time {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func (m *Meta) GetUpdatedTime() *time.Time {
	if m != nil {
		return m.UpdatedTime
	}
	return nil
}

func (m *Meta) GetDeletedTime() *time.Time {
	if m != nil {
		return m.DeletedTime
	}
	return nil
}

func init() {
	proto.RegisterType((*Meta)(nil), "activeiot.core.v1.Meta")
}

func init() { proto.RegisterFile("api/proto/core/v1/meta.proto", fileDescriptor_7bf797db7e4df907) }

var fileDescriptor_7bf797db7e4df907 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x4f, 0x4a, 0xc3, 0x40,
	0x14, 0xc6, 0xe7, 0xb5, 0xa5, 0x60, 0xea, 0xa6, 0x05, 0x41, 0x8a, 0xbc, 0x8a, 0x2b, 0x37, 0x4e,
	0x88, 0x9e, 0xa0, 0xcd, 0x5a, 0x28, 0x22, 0x45, 0xa4, 0x20, 0x93, 0x64, 0x8c, 0x81, 0x86, 0x09,
	0x71, 0x92, 0xb5, 0x27, 0x90, 0x9e, 0xc1, 0x95, 0x78, 0x12, 0x71, 0x95, 0x8d, 0xd0, 0x9d, 0x66,
	0xb2, 0x71, 0xd9, 0x23, 0xc8, 0xe4, 0x4f, 0x2b, 0xb8, 0xe9, 0x6e, 0xe6, 0x37, 0xdf, 0xf7, 0x9b,
	0xc7, 0x33, 0x8e, 0x58, 0x14, 0x98, 0x51, 0x2c, 0xa4, 0x30, 0x5d, 0x11, 0x73, 0x33, 0xb5, 0xcc,
	0x90, 0x4b, 0x46, 0x4b, 0x34, 0xe8, 0x33, 0x57, 0x06, 0x29, 0x0f, 0x84, 0xa4, 0xfa, 0x95, 0xa6,
	0xd6, 0xf0, 0xcc, 0x0f, 0xe4, 0x43, 0xe2, 0x50, 0x57, 0x84, 0xa6, 0x2f, 0x7c, 0x51, 0x95, 0x9d,
	0xe4, 0xbe, 0xbc, 0x55, 0x26, 0x7d, 0xaa, 0x0c, 0xc3, 0x91, 0x2f, 0x84, 0xbf, 0xe0, 0xdb, 0x94,
	0x0c, 0x42, 0xfe, 0x28, 0x59, 0x18, 0x55, 0x81, 0x93, 0x4f, 0x30, 0x3a, 0x97, 0x5c, 0xb2, 0x81,
	0x6d, 0xec, 0xbb, 0x31, 0x67, 0x92, 0x7b, 0x77, 0x3a, 0x73, 0x08, 0xc7, 0x70, 0xda, 0x3b, 0x1f,
	0xd2, 0x4a, 0x40, 0x1b, 0x01, 0xbd, 0x6e, 0x04, 0x93, 0xce, 0xf2, 0x6b, 0x04, 0x57, 0xbd, 0xba,
	0xa5, 0xb9, 0x96, 0x24, 0x91, 0xb7, 0x95, 0xb4, 0x76, 0x95, 0xd4, 0xad, 0x46, 0xe2, 0xf1, 0x05,
	0xdf, 0x48, 0xda, 0xbb, 0x4a, 0xea, 0x96, 0xe6, 0x93, 0x67, 0xc8, 0x72, 0x24, 0xab, 0x1c, 0xc9,
	0x3a, 0x47, 0x78, 0x52, 0x08, 0xaf, 0x0a, 0xe1, 0x5d, 0x21, 0x64, 0x0a, 0xe1, 0x5b, 0x21, 0xfc,
	0x28, 0x24, 0x6b, 0x85, 0xb0, 0x2c, 0x90, 0x64, 0x05, 0x92, 0x55, 0x81, 0xc4, 0x38, 0x70, 0x45,
	0x48, 0xff, 0x6d, 0x7d, 0xb2, 0xa7, 0x57, 0x34, 0xd5, 0x1f, 0x4f, 0xe1, 0xb6, 0xab, 0x69, 0x6a,
	0xbd, 0xb4, 0xda, 0x63, 0xfb, 0xe6, 0xad, 0xd5, 0x1f, 0x6f, 0xe2, 0xb6, 0x8e, 0xcf, 0xac, 0x8f,
	0x3f, 0x6c, 0xae, 0xd9, 0x7c, 0x66, 0x39, 0xdd, 0x72, 0xee, 0x8b, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xa6, 0x00, 0x71, 0x31, 0xf2, 0x01, 0x00, 0x00,
}

func (this *Meta) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Meta)
	if !ok {
		that2, ok := that.(Meta)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if that1.CreatedTime == nil {
		if this.CreatedTime != nil {
			return false
		}
	} else if !this.CreatedTime.Equal(*that1.CreatedTime) {
		return false
	}
	if that1.UpdatedTime == nil {
		if this.UpdatedTime != nil {
			return false
		}
	} else if !this.UpdatedTime.Equal(*that1.UpdatedTime) {
		return false
	}
	if that1.DeletedTime == nil {
		if this.DeletedTime != nil {
			return false
		}
	} else if !this.DeletedTime.Equal(*that1.DeletedTime) {
		return false
	}
	return true
}
func (this *Meta) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&corev1.Meta{")
	s = append(s, "CreatedTime: "+fmt.Sprintf("%#v", this.CreatedTime)+",\n")
	s = append(s, "UpdatedTime: "+fmt.Sprintf("%#v", this.UpdatedTime)+",\n")
	s = append(s, "DeletedTime: "+fmt.Sprintf("%#v", this.DeletedTime)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringMeta(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *Meta) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Meta) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.CreatedTime != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMeta(dAtA, i, uint64(github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreatedTime)))
		n1, err := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.CreatedTime, dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.UpdatedTime != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintMeta(dAtA, i, uint64(github_com_gogo_protobuf_types.SizeOfStdTime(*m.UpdatedTime)))
		n2, err := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.UpdatedTime, dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.DeletedTime != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintMeta(dAtA, i, uint64(github_com_gogo_protobuf_types.SizeOfStdTime(*m.DeletedTime)))
		n3, err := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.DeletedTime, dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	return i, nil
}

func encodeVarintMeta(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Meta) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CreatedTime != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreatedTime)
		n += 1 + l + sovMeta(uint64(l))
	}
	if m.UpdatedTime != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.UpdatedTime)
		n += 1 + l + sovMeta(uint64(l))
	}
	if m.DeletedTime != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.DeletedTime)
		n += 1 + l + sovMeta(uint64(l))
	}
	return n
}

func sovMeta(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozMeta(x uint64) (n int) {
	return sovMeta(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Meta) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Meta{`,
		`CreatedTime:` + strings.Replace(fmt.Sprintf("%v", this.CreatedTime), "Timestamp", "types.Timestamp", 1) + `,`,
		`UpdatedTime:` + strings.Replace(fmt.Sprintf("%v", this.UpdatedTime), "Timestamp", "types.Timestamp", 1) + `,`,
		`DeletedTime:` + strings.Replace(fmt.Sprintf("%v", this.DeletedTime), "Timestamp", "types.Timestamp", 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringMeta(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Meta) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMeta
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Meta: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Meta: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMeta
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMeta
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreatedTime == nil {
				m.CreatedTime = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.CreatedTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMeta
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMeta
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UpdatedTime == nil {
				m.UpdatedTime = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.UpdatedTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeletedTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMeta
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMeta
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DeletedTime == nil {
				m.DeletedTime = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.DeletedTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMeta(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMeta
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMeta
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMeta(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMeta
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMeta
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthMeta
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowMeta
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipMeta(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthMeta
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthMeta = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMeta   = fmt.Errorf("proto: integer overflow")
)
